apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-techdocs-test2
  annotations:
    github.com/project-slug: ndennis-fanduel/backstage-techdocs-test2
spec:
  type: other
  lifecycle: unknown
  owner: guests
